# Generated by Django 5.2.8 on 2025-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("max", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
    ]
