# Generated by Django 6.0 on 2025-12-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("max", "0003_remove_node_latitude_remove_node_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="role",
            field=models.IntegerField(choices=[(0, "Repeater"), (1, "Client")], default=0),
        ),
    ]
