# Generated by Django 6.0 on 2025-12-28 15:00

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotspotConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ssid", models.CharField(blank=True, help_text="WiFi hotspot SSID", max_length=255)),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text="Encrypted WiFi password"),
                ),
            ],
            options={
                "verbose_name": "Hotspot Configuration",
                "verbose_name_plural": "Hotspot Configuration",
            },
        ),
    ]
